services:
  influxdb:
    image: influxdb:2.7
    container_name: ap_influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword123
      DOCKER_INFLUXDB_INIT_ORG: SRH
      DOCKER_INFLUXDB_INIT_BUCKET: production_line
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: srh-token-123
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: ap_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:
