apiVersion: 1

datasources:
  - name: InfluxDB-Pencil-Line
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: SRH
      defaultBucket: production_line
      tlsSkipVerify: true
    secureJsonData:
      token: srh-token-123
